-- Installment transactions are already scheduled on their payment dates.
-- Credit-card billing cycles apply only to standalone purchases, not to
-- installments generated by an installment plan.

UPDATE transactions
SET payment_date = transaction_date,
    status = CASE
        WHEN status = 'RECONCILED' THEN status
        WHEN transaction_date > CURRENT_DATE THEN 'PLANNED'
        ELSE 'CLEARED'
    END
WHERE installment_plan_id IS NOT NULL
  AND payment_date <> transaction_date;
