-- User lifecycle (admin approval), admin flag, and plan tier.

ALTER TABLE users ADD COLUMN IF NOT EXISTS approved BOOLEAN;
UPDATE users SET approved = TRUE WHERE approved IS NULL;
ALTER TABLE users ALTER COLUMN approved SET DEFAULT FALSE;
ALTER TABLE users ALTER COLUMN approved SET NOT NULL;

ALTER TABLE users ADD COLUMN IF NOT EXISTS admin BOOLEAN;
UPDATE users SET admin = FALSE WHERE admin IS NULL;
ALTER TABLE users ALTER COLUMN admin SET DEFAULT FALSE;
ALTER TABLE users ALTER COLUMN admin SET NOT NULL;

ALTER TABLE users ADD COLUMN IF NOT EXISTS plan VARCHAR(20);
UPDATE users SET plan = 'STANDARD' WHERE plan IS NULL OR TRIM(plan) = '';
ALTER TABLE users ALTER COLUMN plan SET DEFAULT 'STANDARD';
ALTER TABLE users ALTER COLUMN plan SET NOT NULL;
ALTER TABLE users ADD CONSTRAINT chk_users_plan
    CHECK (plan IN ('STANDARD', 'PREMIUM'));
