import React from 'react'
import {
  Pulse as Activity,
  WarningCircle as AlertCircle,
  Warning as AlertTriangle,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  ChartBar as BarChart3,
  Briefcase,
  Buildings as Building,
  Calculator,
  Calendar,
  CalendarCheck,
  CalendarDots as CalendarClock,
  CalendarBlank as CalendarDays,
  Car,
  ChartBar as ChartColumn,
  Check,
  CheckCircle as CheckCircle2,
  CaretDown as ChevronDown,
  CaretLeft as ChevronLeft,
  CaretRight as ChevronRight,
  CaretUp as ChevronUp,
  Clock,
  Coffee,
  CreditCard,
  Database,
  CurrencyGbp as DollarSign,
  Barbell as Dumbbell,
  Eye,
  EyeSlash as EyeOff,
  FileText,
  FilmStrip as Film,
  Funnel as Filter,
  GameController as Gamepad2,
  Gear,
  Gear as Settings,
  Gift,
  GraduationCap,
  Heart,
  House as Home,
  Laptop,
  Stack as Layers,
  SquaresFour as LayoutDashboard,
  Lightbulb,
  ChartLineUp as LineChart,
  List,
  FunnelSimple as ListFilter,
  Lock,
  SignOut as LogOut,
  Envelope as Mail,
  Chat as MessageSquare,
  Minus,
  Moon,
  MusicNote as Music,
  PencilSimple as Pencil,
  Percent,
  ChartPieSlice as PieChart,
  Plus,
  Receipt,
  ArrowsClockwise as RefreshCw,
  ArrowsClockwise as Repeat,
  ArrowCounterClockwise as RotateCcw,
  MagnifyingGlass as Search,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Smiley as Smile,
  DeviceMobile as Smartphone,
  Sparkle as Sparkles,
  Sun,
  Tag,
  Trash as Trash2,
  TrendDown as TrendingDown,
  TrendUp as TrendingUp,
  User,
  Wallet,
  X,
  Lightning as Zap,
  IconProps
} from '@phosphor-icons/react'

export type LucideIcon = React.FC<IconProps>

export {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  BarChart3,
  Briefcase,
  Building,
  Calculator,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  Calendar as CalendarRange,
  Car,
  ChartColumn,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Coffee,
  CreditCard,
  Database,
  DollarSign,
  Dumbbell,
  Eye,
  EyeOff,
  FileText,
  Film,
  Filter,
  Gamepad2,
  Gift,
  GraduationCap,
  Heart,
  Home,
  Laptop,
  Layers,
  LayoutDashboard,
  Lightbulb,
  LineChart,
  List,
  ListFilter,
  Lock,
  LogOut,
  Mail,
  MessageSquare,
  Minus,
  Moon,
  Music,
  Pencil,
  Percent,
  PieChart,
  Plus,
  Receipt as ReceiptText,
  RefreshCw,
  Repeat,
  RotateCcw,
  Search,
  Settings,
  Gear,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Smile,
  Smartphone,
  Sparkles,
  Sun,
  Tag,
  Trash2,
  TrendingDown,
  TrendingUp,
  User,
  Wallet,
  X,
  Zap
}
