import React from 'react'
import {
  Pulse as Activity,
  WarningCircle as AlertCircle,
  Warning as AlertTriangle,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Backspace,
  ChartBar as BarChart3,
  BriefcaseIcon as Briefcase,
  Broom,
  BuildingsIcon as Building,
  BookOpenIcon as BookOpen,
  Calculator,
  Calendar,
  CalendarCheck,
  CalendarDots as CalendarClock,
  CalendarBlank as CalendarDays,
  CarIcon as Car,
  ChartBar as ChartColumn,
  ChartLineUp,
  Check,
  CheckCircle as CheckCircle2,
  CaretDown as ChevronDown,
  CaretLeft as ChevronLeft,
  CaretRight as ChevronRight,
  CaretUp as ChevronUp,
  Clock,
  CoffeeIcon as Coffee,
  CookingPot,
  CreditCard,
  Bell,
  Database,
  Drop,
  DownloadSimple as Download,
  UploadSimple as Upload,
  CurrencyGbpIcon as DollarSign,
  GlobeHemisphereWestIcon as Globe,
  Barbell as Dumbbell,
  Eye,
  EyeSlash as EyeOff,
  FileText,
  FilmStripIcon as Film,
  Flame,
  Funnel as Filter,
  GameControllerIcon as Gamepad2,
  Gear,
  Gear as Settings,
  GiftIcon as Gift,
  GraduationCapIcon as GraduationCap,
  HeartIcon as Heart,
  HouseIcon as Home,
  Laptop,
  Stack as Layers,
  SquaresFour as LayoutDashboard,
  Lightbulb,
  ChartLineUp as LineChart,
  List,
  FunnelSimple as ListFilter,
  Lock,
  SignOut as LogOut,
  Envelope as Mail,
  Chat as MessageSquare,
  Minus,
  Moon,
  MusicNoteIcon as Music,
  PencilSimple as Pencil,
  Percent,
  Plant,
  ChartPieSlice as PieChart,
  Plus,
  ReceiptIcon as Receipt,
  ArrowsClockwise as RefreshCw,
  ArrowsClockwise as Repeat,
  ArrowCounterClockwise as RotateCcw,
  MagnifyingGlass as Search,
  ShieldIcon as Shield,
  ShieldCheck,
  ShoppingBagIcon as ShoppingBag,
  ShoppingCartIcon as ShoppingCart,
  Smiley as Smile,
  DeviceMobile as Smartphone,
  Sparkle as Sparkles,
  Sidebar as SidebarSimple,
  CaretDoubleLeft,
  Sun,
  Tag,
  ToiletPaper,
  Trash as Trash2,
  TrendDown as TrendingDown,
  TrendUpIcon as TrendingUp,
  User,
  Users,
  WalletIcon as Wallet,
  WifiHigh,
  X,
  LightningIcon as Zap,
  IconProps
} from '@phosphor-icons/react'

export type LucideIcon = React.FC<IconProps>

/** Lightweight rent-specific mark: a welcoming home paired with a small key. */
export const RentHome: LucideIcon = ({
  color = 'currentColor',
  mirrored = false,
  size = 24,
  style,
  weight = 'regular',
  ...props
}) => {
  const strokeWidth = weight === 'thin' ? 1 : weight === 'light' ? 1.5 : weight === 'bold' ? 2.5 : 2

  return React.createElement(
    'svg',
    {
      ...props,
      width: size,
      height: size,
      viewBox: '0 0 24 24',
      fill: 'none',
      stroke: color,
      strokeWidth,
      strokeLinecap: 'round',
      strokeLinejoin: 'round',
      style: { ...style, transform: mirrored ? 'scaleX(-1)' : style?.transform },
    },
    React.createElement('path', { d: 'M3.75 10.5 12 3.75l8.25 6.75v8a1.75 1.75 0 0 1-1.75 1.75h-13a1.75 1.75 0 0 1-1.75-1.75Z' }),
    React.createElement('path', { d: 'M8.75 20.25V15.5a1.5 1.5 0 0 1 1.5-1.5h2.5a1.5 1.5 0 0 1 1.5 1.5v4.75' }),
    React.createElement('circle', { cx: '16.75', cy: '11.25', r: '1.5' }),
    React.createElement('path', { d: 'M18.25 11.25h2.25m-1 0v1.25' }),
  )
}

export {
  Activity,
  AlertCircle,
  AlertTriangle,
  Bell,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Backspace,
  BarChart3,
  BookOpen,
  Briefcase,
  Broom,
  Building,
  Calculator,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  Calendar as CalendarRange,
  Car,
  ChartColumn,
  ChartLineUp,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Coffee,
  CookingPot,
  CreditCard,
  Database,
  Drop,
  Download,
  Upload,
  DollarSign,
  Globe,
  Dumbbell,
  Eye,
  EyeOff,
  FileText,
  Film,
  Flame,
  Filter,
  Gamepad2,
  Gift,
  GraduationCap,
  Heart,
  Home,
  Laptop,
  Layers,
  LayoutDashboard,
  Lightbulb,
  LineChart,
  List,
  ListFilter,
  Lock,
  LogOut,
  Mail,
  MessageSquare,
  Minus,
  Moon,
  Music,
  Pencil,
  Percent,
  PieChart,
  Plant,
  Plus,
  Receipt as ReceiptText,
  RefreshCw,
  Repeat,
  RotateCcw,
  Search,
  Settings,
  Gear,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Smile,
  Smartphone,
  Sparkles,
  Sun,
  Tag,
  ToiletPaper,
  Trash2,
  TrendingDown,
  TrendingUp,
  User,
  Users,
  Wallet,
  WifiHigh,
  X,
  Zap,
  SidebarSimple,
  CaretDoubleLeft
}
