package com.example.budget.model;

public enum HouseholdNotificationType {
    EXPENSE_CREATED,
    EXPENSE_UPDATED,
    EXPENSE_VOIDED,
    SETTLEMENT_CREATED,
    SETTLEMENT_CONFIRMED,
    SETTLEMENT_REJECTED,
    SETTLEMENT_CANCELLED,
    MEMBER_JOINED,
    MEMBER_REMOVED,
    CLEANING_WEEK_ASSIGNED,
    CLEANING_DUTY_COMPLETED,
    CLEANING_WEEK_COMPLETED
}
